### PR TITLE
Add support for http basic auth

### PR DESCRIPTION
**Pull request by chris-scentregroup**
This also introduced the needed use of a general handler for the proxy so that we can intercept requests early on before creating the reverse proxy and passing it on.

Default realm and user is set, it requires the user to set a password for it to be in play (and optionally change the username and realm).

### CODE REVIEW

**Review by acoshift — CHANGES_REQUESTED** [review]
ReverseProxy should be create only 1 time outside the handler.
If you don't mind I can refactor them.

**Comment by chris-scentregroup** [comment]
@acoshift definitely keen to see that and also learn from it :)
Please feel free to append.

**Comment by flaccid** [comment]
Understood what you meant there now, oversight on my behalf. Pushed https://github.com/acoshift/revprox/pull/4/commits/71cb09c4891a0557f46e91971ff3844d82d1dca3.

**Comment by acoshift** [comment]
I just refactor and I will bump version on another PR.

**Review by acoshift — APPROVED** [review]

**Comment by acoshift** [comment]
wow, I just forget to push to main.go will fix this now

**Comment by chris-scentregroup** [comment]
gotcha, was trying my best to not bump up for real, but i I like what you did there!

**Pull request merged**
